import { z } from "zod";

const envSchema = z.object({
  NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1),
  NEXT_PUBLIC_OPENCLAW_GATEWAY_WS_URL: z.string().min(1),
  NEXT_PUBLIC_OPENCLAW_OPERATOR_TOKEN: z.string().optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().optional()
});

export const env = envSchema.parse({
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  NEXT_PUBLIC_OPENCLAW_GATEWAY_WS_URL: process.env.NEXT_PUBLIC_OPENCLAW_GATEWAY_WS_URL,
  NEXT_PUBLIC_OPENCLAW_OPERATOR_TOKEN: process.env.NEXT_PUBLIC_OPENCLAW_OPERATOR_TOKEN,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY
});

